version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    container_name: integration-tests
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tests

  redis:
    image: redis
    ports:
      - 6379:6379